# Generated by Django 5.0.6 on 2024-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('adresse', models.CharField(max_length=150, verbose_name='Adresse')),
                ('info', models.TextField(verbose_name='Informationen')),
            ],
            options={
                'verbose_name': 'Ausbilder',
                'verbose_name_plural': 'Ausbilder',
            },
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=20, verbose_name='Gruppe')),
                ('start', models.DateField(verbose_name='Start der Ausbildung')),
                ('ende', models.DateField(verbose_name='Ende der Ausbildung(Prüfung)')),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
    ]
