# Generated by Django 5.0.6 on 2024-06-29 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('inhalt', models.TextField(verbose_name='Inhalt')),
                ('hauptausbilder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildung.ausbilder', verbose_name='Hauptausbilder')),
            ],
            options={
                'verbose_name': 'Fach',
                'verbose_name_plural': 'Fächer',
            },
        ),
    ]
