# Generated by Django 5.0.6 on 2024-06-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildung', '0002_fach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('inhalt', models.TextField(verbose_name='Inhalt')),
                ('laenge', models.IntegerField(verbose_name='Länge')),
                ('fach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildung.fach', verbose_name='Fach')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themas',
            },
        ),
    ]
