# Generated by Django 5.0.6 on 2024-06-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildung', '0003_thema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbildungseinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Thema')),
                ('datum', models.DateTimeField(verbose_name='Datum')),
                ('laenge', models.IntegerField(verbose_name='Länge')),
                ('ausbilder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildung.ausbilder', verbose_name='Ausbilder')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildung.gruppe', verbose_name='Gruppe')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ausbildung.thema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Ausbildungseinheit',
                'verbose_name_plural': 'Ausbildungseinheiten',
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Schüler')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausbildung.gruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Schüler',
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.CreateModel(
            name='Lernerfolgskontrolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(verbose_name='Datum')),
                ('punkte', models.IntegerField(verbose_name='Punkte')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausbildung.thema', verbose_name='Thema')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausbildung.schueler', verbose_name='Schüler')),
            ],
            options={
                'verbose_name': 'Lernerfolgskontrolle',
                'verbose_name_plural': 'Lernerfolgskontrollen',
            },
        ),
    ]
